### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by libregeek** [chriskottom/fbo#1]
I got the following error on executing `rfile = FBO::RemoteFile.new(filename, options)` in my script:

```
/usr/share/ruby/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /usr/share/ruby/net/protocol.rb:152:in `rbuf_fill'
	from /usr/share/ruby/net/protocol.rb:134:in `readuntil'
	from /usr/share/ruby/net/ftp.rb:1105:in `gets'
	from /usr/share/ruby/net/ftp.rb:1110:in `readline'
	from /usr/share/ruby/net/ftp.rb:289:in `getline'
	from /usr/share/ruby/net/ftp.rb:300:in `getmultiline'
	from /usr/share/ruby/net/ftp.rb:318:in `getresp'
	from /usr/share/ruby/net/ftp.rb:338:in `voidresp'
	from /usr/share/ruby/net/ftp.rb:361:in `block in voidcmd'
	from /usr/share/ruby/monitor.rb:211:in `mon_synchronize'
	from /usr/share/ruby/net/ftp.rb:359:in `voidcmd'
	from /usr/share/ruby/net/ftp.rb:375:in `sendport'
	from /usr/share/ruby/net/ftp.rb:386:in `makeport'
	from /usr/share/ruby/net/ftp.rb:421:in `transfercmd'
	from /usr/share/ruby/net/ftp.rb:490:in `block (2 levels) in retrbinary'
	from /usr/share/ruby/net/ftp.rb:199:in `with_binary'
	from /usr/share/ruby/net/ftp.rb:488:in `block in retrbinary'
	from /usr/share/ruby/monitor.rb:211:in `mon_synchronize'
	from /usr/share/ruby/net/ftp.rb:487:in `retrbinary'
	from /usr/share/ruby/net/ftp.rb:620:in `getbinaryfile'
	from /usr/local/share/gems/gems/fbo-0.1.6/lib/fbo/remote_file.rb:29:in `fetch_file'
	from /usr/local/share/gems/gems/fbo-0.1.6/lib/fbo/remote_file.rb:19:in `initialize'
	from fbo-bot-ftp.rb:43:in `new'
	from fbo-bot-ftp.rb:43:in `<main>'
```
The above error is from a CentOS server running ruby 2.0.0p648 (2015-12-16) [x86_64-linux]. I am able to connect to the FBO ftp server from CLI.

The script works without any issues from my desktop (which runs ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]).

I searched for solutions in SO, and most of them suggests increasing the timeout value (read_timeout). But I don't think that's the root cause since I am able to run the script from my desktop. Is it due to the version of Ruby? Any thoughts?

**Comment by chriskottom** [comment]
The problem is unlikely to be related to the Ruby version you're using (a simple script I wrote run against that version works) but rather the network conditions from that server. There's not enough here to diagnose the problem, but in the worst case, wrap your Ruby parser in a shell script that uses the system FTP client to fetch the file from the server.

**Comment by libregeek** [comment]
Thanks for your quick reply. I installed ruby-2.3 from CentOS Software Collection and it worked whenever I switched to 2.3.
