### ISSUE TITLE
Docs!

### ISSUE THREAD

**Issue by prostko** [chriskottom/fbo#2]
Usage?

**Comment by chriskottom** [comment]
I updated the README with some basic information about how the gem works based on the `fbo_parser` executable that's in the `bin/` directory.  That gives a pretty good sense for what's possible and a pattern for using it.

As you see from the commit history, this is something that I'm no longer actively working on, but I've been meaning to do a bit of cleanup on it for a while now.  If you'd like to take it over, I'd be happy to let you, or you're always welcome to fork your own version.
